### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by skinheadz** [Virtuswap/v1-core#77]
god bless your idea to make one big pool containing all the stable/weth tokens for popular tokens, but, please, save my eyesight, make a dark theme default for your main website. we are in web3 after all. god speed 🚀

**Comment by Virtuswap** [comment]
Hello @skinheadz,

We appreciate your feedback! 
Actually a dark theme for the main website is already in development and will be published in the next few days. 
Stay tuned!
